### DISCUSSION TITLE
Gradient Animation Combos

### DISCUSSION THREAD

**Discussion by argyleink** [argyleink/open-props#120] [Ideas]
```css
.box {
  background: var(--gradient-shine), var(--gradient-4);
  
  &:hover {
    animation: var(--gradient-shine-animation);
  }
}
```

which is backed by the following props:

```css
:root {
  --gradient-shine: linear-gradient(120deg, 
    #fff0 45%, 0%,
    #fff4 50%, 0%,
    #fff0 calc(50% + 10px), 0%,
    #fff7 calc(50% + 30px), 0%,
    #fff0 calc(50% + 40px), 0%,
    #fff4 calc(50% + 50px), 0%,
    #fff0 0%
  ) 100% / 300% 100%;
  --gradient-shine-animation: shine 2s ease infinite;
}

@keyframes shine {
  /*  1s effect, 1s hold  */
  50%, 100% {
    background-position-x: 0%;    
  }
}
```

see codepen https://codepen.io/argyleink/pen/oNGzpgO?editors=1100

is this too confusing to use? does it fit within Open Props?
