### DISCUSSION TITLE
Design of sizes props

### DISCUSSION THREAD

**Discussion by airen** [argyleink/open-props#128] [General]
Although the current size props design is very good, I think he still lacks a little something. It is now neither based on 4-point grid nor 8-point grid. in the use of size (such as font size, spacing, etc.) is in many cases a multiple of them. I prefer the 4-point grid because it is more flexible. 

Can the design of size props in open props take these rules into account?

### 4-point grid

![image](https://user-images.githubusercontent.com/368462/146480675-b4a072f7-d7fd-4abc-9357-fc4674d6a793.png)

```css
:root{
    --size-base-point: .25rem;
    --sizes-1: calc(var(--size-base-point) * 1);
    --sizes-2: calc(var(--size-base-point) * 2);
    --sizes-3: calc(var(--size-base-point) * 3);
    --sizes-4: calc(var(--size-base-point) * 4);
    /* ... */
    --sizes-N: calc(var(--size-base-point) * N);
}
```

#### 8-point grid

![image](https://user-images.githubusercontent.com/368462/146481189-be8dc2e0-29b6-474d-a594-b21ee3e514a1.png)

```css
:root{
    --size-base-point: .5rem;
    --sizes-1: calc(var(--size-base-point) * 1);
    --sizes-2: calc(var(--size-base-point) * 2);
    --sizes-3: calc(var(--size-base-point) * 3);
    --sizes-4: calc(var(--size-base-point) * 4);
    /* ... */
    --sizes-N: calc(var(--size-base-point) * N);
}
```

#### Resources

- [The 8-Point Grid](https://spec.fm/specifics/8-pt-grid)
- [How to manage space in Figma using tokens](https://uxdesign.cc/how-to-manage-space-in-figma-using-tokens-8d0ebd99ee1b)
- [The Comprehensive 8pt Grid Guide](https://medium.com/swlh/design-system-based-on-the-8pt-grid-2473ca5f0ae1)
- [Goodbye 8-point grid, hello 4-point grid?](https://uxdesign.cc/goodbye-8-point-grid-hello-4-point-grid-1aa7f2159051)
