### DISCUSSION TITLE
Gooey props

### DISCUSSION THREAD

**Discussion by argyleink** [argyleink/open-props#161] [Ideas]
Get [that gooey effect](https://css-tricks.com/gooey-effect/) with a couple props like:

```css
--gooey: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' version='1.1'%3E%3Cdefs%3E%3Cfilter id='goo'%3E%3CfeGaussianBlur in='SourceGraphic' stdDeviation='10' result='blur' /%3E%3CfeColorMatrix in='blur' mode='matrix' values='1 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 18 -7' result='goo' /%3E%3CfeBlend in='SourceGraphic' in2='goo' /%3E%3C/filter%3E%3C/defs%3E%3C/svg%3E Resources");

.gooey-button-group {
  filter: var(--gooey);
}
```

https://user-images.githubusercontent.com/1134620/150874622-ad64593d-1f6e-4298-8af1-e623cdd61d7c.mp4
