### DISCUSSION TITLE
`scroll-hint` props?

### DISCUSSION THREAD

**Discussion by argyleink** [argyleink/open-props#175] [Q&A]
https://codepen.io/bramus/pen/ExxgNrV

i could see size 1, 2, 3 of these, and offering inline/block variants

the bg needs explicitly fed to the prop (cant be transparent), which means this needs to be in * selector mixin. codepen already has the mixin props ready for size and color. 

```css
@import "open-props/scroll-hints";

.inline-scroller {
  background: var(--scroll-hint-inline-2);
}
```
