### DISCUSSION TITLE
Stagger props

### DISCUSSION THREAD

**Discussion by argyleink** [argyleink/open-props#213] [Ideas]
Extracted from here https://codepen.io/jh3y/pen/OJzJGee, made into reusables OP style down below:

### Stagger

```css
html {
  --stagger-1: calc(var(--index, 0) * 0.05s);
  --stagger-2: calc(var(--index, 0) * 0.1s);
  --stagger-3: calc(var(--index, 0) * 0.15s);
  --stagger-4: calc(var(--index, 0) * 0.25s);
  --stagger-5: calc(var(--index, 0) * 0.5s);
}

.el {
  animation-delay: var(--stagger-2);
}

.el:nth-of-type(1) { --index: 0 }
.el:nth-of-type(2) { --index: 1 }
.el:nth-of-type(3) { --index: 2 }
.el:nth-of-type(4) { --index: 3 }
.el:nth-of-type(5) { --index: 4 }
```

### Reverse Stagger
```css
html {
  --reverse-stagger-1: calc((var(--delay) - var(--index, 0)) * 0.05s);
  --reverse-stagger-2: calc((var(--delay) - var(--index, 0)) * 0.1s);
  --reverse-stagger-3: calc((var(--delay) - var(--index, 0)) * 0.15s);
  --reverse-stagger-4: calc((var(--delay) - var(--index, 0)) * 0.25s);
  --reverse-stagger-5: calc((var(--delay) - var(--index, 0)) * 0.5s);
}

.rev-el {
  --delay: 4;
  animation-delay: var(--reverse-stagger-2);
}

.rev-el:nth-of-type(1) { --index: 0 }
.rev-el:nth-of-type(2) { --index: 1 }
.rev-el:nth-of-type(3) { --index: 2 }
.rev-el:nth-of-type(4) { --index: 3 }
```

@jh3y, thoughts!?
