### DISCUSSION TITLE
Idea to make atomic props responseve

### DISCUSSION THREAD

**Discussion by tobiasschmidt89** [argyleink/open-props#322] [Ideas]
Hi there,

I recently found out that I can do this with custom props:

```css
:root {
  --s4: 1rem;
  --s8: 2rem;
}
@media screen and (min-width: 80ch) { :root {
  --md-s4: var(--s4);
  --md-s8: var(--s8);
  --md-flex: flex;
}}
```

Usage in css.

```css
.card {
  display: var(--md-flex, grid);
  padding: var(--md-s8, var(---s4));
}
```

Responsive atomic custom props feel like tailwind, but only one custom prop is needed per value and breakpoint vs. tailwinds property, value and breakpoint combination. Also it still feels like utility classes, but mixes better with using plain old css vs going full in with utility classes.

Usage in inline styles (jsx) also feels good and comparable to tailwind without the need of crazy tooling:

```html
<Card style="padding:var(--md-s8, var(--s4));" />
```

This basically removes 50% of the reason why we have css-in-js. With some smart choices it is also possible to solve the other 50% of issue: Inline style interactivity. Compared to e.g. space props it is more difficult so to create a set of useful props in a library like open props 

```css
a:hover {
  --h-scale: scale(1.15);
}

```

Usage:

```html
<Card style="transform:var(--h-scale, scale(1));" />
```

Maybe open props can become a responsive, atomic custom prop library with this.

KR
Tobi

**Comment by argyleink** [comment]
Nice, glad you're feelin it and finding workflows!

I see what you've got here as "house props" which you can totally make adaptive/responsive. 

```css
:root {
  --surface-1: var(--gray-1);
  --text-1: var(--gray-10);
}

@media (prefers-color-scheme:dark) {
  :root {
    --surface-1: var(--gray-11);
    --text-1: var(--gray-2);
  }
}

body {
  background: var(--surface-1);
  color: var(--text-1);
}
```

This makes `--surface-1` and `--text-1` adaptive to color scheme. It was initially setup by someone, me in this example, but other team mates later can just use the adaptive props and not worry about what backs them, they just know they get these adaptive atomic custom properties. Can be used in JSX or whatever. 

I definitely think making house props is a great way to architect a back-of-the-front, to help accelerate a team 👍🏻
