### DISCUSSION TITLE
icons.css

### DISCUSSION THREAD

**Discussion by argyleink** [argyleink/open-props#65] [Ideas]
while you can put svg into a string, you can't really provide an api into setting colors n stuff. tho maybe we can get creative? icons as props would be nice.

**Comment by equinusocio** [comment]
@argyleink Just did a poc by using mask-images:
https://codepen.io/equinusocio/pen/QWqVOVm?editors=1100

**Reply by argyleink** [reply]
Very sick demo and starter 🤘🏻💀 brings me much joy! 

jit-props makes file size trivial and usage seamless, but agree we could offer some packs or bundles for minimal usage without PostCSS. Maybe something like `open-props.icons.media.css` which has play/pause icons and whatever?

Where do you think we should source the icons? 

Very exciting!

**Reply by argyleink** [reply]
i didnt see any icon libraries that offer custom properties..! they should.

i'm thinking, like OP's colors and gradients, the icons should piggy back on an existing open source solution / icon source. then the groups are already chosen, there's docs, and even the svg if someone wants it instead of the prop. through an OP build step: grab the open source svg, process each so CSS can take it (and any other funging like to sizing), and then output bundles, very similar to color in that way. for jit-props users they can download the "all" package, just like colors. 

so the question, [which icon library to piggy back on](https://icones.js.org/)? here's some [ideas on twitter folks shared](https://twitter.com/argyleink/status/1480237318971686918). i'm leaning towards material (popular), feather (clean and [js api](https://github.com/feathericons/feather#api-reference)), and..?

**Reply by equinusocio** [reply]
This is a giant tool where you can find icon sets:
https://icones.js.org/

There are many many valid icon sets. I think the specs to follow are:

- Well sized: icons must be designed with the same frame size and grid
- Visually balanced and readable also at small sizes
- More icons the better
- More styles the better (?) if multi-style icons are a thing
- SVG source

**Reply by argyleink** [reply]
what do you think of using the api of icones to allow all of the icones aggregated icons?
[https://codepen.io/argyleink/pen/yLzRXYX](https://codepen.io/argyleink/pen/yLzRXYX)

```css
:root {
  --icon-skull: url("https://api.iconify.design/whh:skull.svg") center / contain no-repeat;
  --icon-dots: url("https://api.iconify.design/mdi:ferris-wheel.svg") center / contain no-repeat;
  --icon-cloud: url("https://api.iconify.design/mdi:apple-icloud.svg") center / contain no-repeat;
}
```

then using the `mask` shorthand:

```css
[name="cloud"] {
  mask: var(--icon-cloud);
  background: var(--gradient-1);
  animation: var(--animation-float);
}
```

![Screen Shot 2022-01-10 at 5 37 00 PM](https://user-images.githubusercontent.com/1134620/148866129-dd6e95df-8749-45a6-a9f2-bb27c215a0e8.png)

are there build tools / css plugins that fetch those CSS remote urls and embed them? that's be sweet if during dev you could use the url and play around, while a prod build inlined them so the css file didnt come with dependencies.
