### ISSUE TITLE
Shadow Customization

### ISSUE THREAD

**Issue by crswll** [argyleink/open-props#124]
Playing around with Open Props to expand my horizons a bit and came across a situation I'm curious to know how you handle.

Looking at the shadows props there's `--shadow-strength` and `--shadow-color` and I'm curious how you go about changing those (or if you're even supposed to).

```css
:where(html) {
  --shadow-color: 220 3% 15%;
  --shadow-strength: 1%;
  --shadow-1: 0 1px 2px -1px hsl(var(--shadow-color) / calc(var(--shadow-strength) + 9%));
  --shadow-2: 
    0 3px 5px -2px hsl(var(--shadow-color) / calc(var(--shadow-strength) + 3%)),
    0 7px 14px -5px hsl(var(--shadow-color) / calc(var(--shadow-strength) + 5%));
  /* ... */
}
```

**Comment by argyleink** [comment]
i'd say you generally don't need to change these. they're what's flipped in a `(prefers-color-scheme: dark)` so the shadows are adaptive to light/dark themes.

you're free to change them tho! easily overwritten with `html { --shadow-strength: 5% }`

here's [the line of code](https://github.com/argyleink/open-props/blob/main/src/props.shadows.css#L44) that flips those vars. these vars, and the media query, ship with the open-props bundle.

got more Qs!? get the answers you were lookin for?! 🙂

**Comment by crswll** [comment]
Yes but now I am very confused in other ways.

```css
:where(:root) {
  --shadow-color: red;
  --shadow-test: 5px 5px 10px var(--shadow-color)
}

// This works just fine...
html {
  --shadow-color: blue;
}

.some-cool-button {
  box-shadow: var(--shadow-test);
}
```


```css
:where(:root) {
  --shadow-color: red;
  --shadow-test: 5px 5px 10px var(--shadow-color)
}

// This does not...
.some-cool-button {
  --shadow-color: blue;
  box-shadow: var(--shadow-test)
}
```

I think I get why but it seems a little limiting to only be able to do it at `html`.
