### ISSUE TITLE
Add way to change linear gradient direction

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#16]
something like?

```css
.box {
  --op-gradient-direction: to bottom right;
  background-image: var(--gradient-1);
}
```
