### ISSUE TITLE
Update normalize, theme and brand with naming convention for house props

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#160]

**Comment by argyleink** [comment]
this would be a breaking change:

old:
```css
.card {
  background: var(--surface-1);
  color: var(--text-1);
}
```

new:
```css
.card {
  background: var(--_surface-1);
  color: var(--_text-1);
}
```

reasoning is that these props from normalize aren't Open Props generic, they're named with jargon for a design system. since they're kinda different, name them different to help distinguish them from the rest. but maybe it's trivial and silly?
