### ISSUE TITLE
touch action props?

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#2]
they're hard to remember, and sorta act opposite than what you think. we could provide named aliases for "sets" or "certain functionality" that makes it much easier to drop these in.

```css
.map {
  touch-action: var(--touch-action-custom-touch-y-handling);
}
```
