### ISSUE TITLE
:focus-visible not respecting the outline-color

### ISSUE THREAD

**Issue by Skil3e** [argyleink/open-props#270]
Not sure if it is intentional but  ```outline-color``` does not work alone.

A fix i found is to add ```outline-style : solid;``` on the ```theme.css``` file so it respects the rule.
```css
/* :file src/extra/theme.css */
:focus-visible {
  outline-style : solid;
  outline-color : var(--link);
}
```
