### ISSUE TITLE
Add `container-type: inline-size;` to normalize

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#328]
- [ ] research side effects
- [ ] try it on a site or two
- [ ] [add the style to the normalize](https://github.com/argyleink/open-props/blob/main/src/extra/normalize.src.css#L40-L42) and make a PR

```css
body {
  container-type: inline-size;
}
```
