### ISSUE TITLE
add fold env var named props

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#372]
there is probably a whole set of segment viewport vars to make:

```css
:root {
  --fold-1: env(viewport-segment-left 1 0);
  --fold-2: env(viewport-segment-left 0 0);
  --size-hinge: calc(var(--fold-1) - var(--fold-2));
}

.layout {
  display: grid;
  grid-template-columns: var(--fold-1) var(--fold-2);
  gap: var(--size-hinge);
}
```
