### ISSUE TITLE
props.supports.js

### ISSUE THREAD

**Issue by woodcox** [argyleink/open-props#380]
There is a `props.supports.css` file in the `src` folder. But there is no `props.supports.js` is there a reason for this? 

Could one be created? I thought the css was complied from js across the repo.

**Comment by argyleink** [comment]
no big reason, it's just not a file I promote as it's generally best to try and avoid browser specific support queries. it could get a js file and a build process tho, but havent had a reason to yet.

**Comment by cbontems** [comment]
I agree with avoiding browser specific support, but maybe this could be a good use case:
```css
@media (--HDcolors) {
  @supports (--colorP3) {
    color: color(display-p3 0 .5 1);
  }
}
```
