### ISSUE TITLE
gradients should auto upgrade to `oklab` and HDR

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#397]

**Comment by mobalti** [comment]
I think for the colors it's okay, but for the gradients, we have to wait for Firefox support.
https://developer.mozilla.org/en-US/docs/Web/CSS/hue-interpolation-method

**Comment by mobalti** [comment]
In the meantime, we also need more gradients.

**Comment by argyleink** [comment]
this could be something like:

```css
:root {
  --space: ;
  --gradient-1: linear-gradient(to right var(--space), red, blue);
  --gradient-2: …;
  --gradient-3: …;
}

@supports (background: linear-gradient(to right in oklab, #000, #fff)) {
  :root {
    --space: in oklab;
  }
}
```
