### ISSUE TITLE
add `hanging-punctuation`

### ISSUE THREAD

**Issue by jacobthesheep** [argyleink/open-props#442]
https://caniuse.com/?search=hanging-punctuation
https://chriscoyier.net/2023/11/27/the-hanging-punctuation-property-in-css/

**Comment by argyleink** [comment]
nice! like adding this to normalize is what you're thinking?

```css
blockquote {
  hanging-punctuation: first last;

  &::before {
    content: open-quote;
  }

  &::after {
    content: close-quote;
  }
}
```
