### ISSUE TITLE
Enable smooth scrolling for nested scrollers also

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#460]
Currently the style only applies to the root scroller `html`, missing nested scrollers. This will match any of them that use url hash targets inside.

```css
@media (--motionOK) {
  :where(:has(:target)) {
    scroll-behavior: smooth;
  }
}
```
