### ISSUE TITLE
Add social media brand colors pack

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#471]
```css
:where(html) {
  --facebook: #1877f2;
  --facebook-old: #3b5998;
  --twitter: #1da1f2;
  --youtube: #ff0000;
  --instagram: #c32aa3;
  --instagram-blue: #4c5fd7;
  --instagram-purple: #7232bd;
  --instagram-orange: #f46f30;
  --instagram-yellow: #ffdc7d;
  --google-blue: #4285f4;
  --google-red: #ea4335;
  --google-yellow: #fbbc05;
  --google-green: #34a853;
  --pinterest: #bd081c;
  --snapchat: #fffc00;
  --whatsapp: #25d366;
  --whatsapp-teal: #075e54;
  --whatsapp-teal2: #128c7e;
  --tiktok-black: #010101;
  --tiktok-blue: #69c9d0;
  --tiktok-pink: #ee1d52;
  --tiktok-white: #fff;
  --mastodon: #563acc;
  --apple: #a6b1b7;
  --amazon: #ff9900;
  --alexa: #00a7ce;
  --microsoft-red: #f35022;
  --microsoft-green: #80bb03;
  --microsoft-blue: #03a5f0;
  --microsoft-yellow: #ffb903;
  --periscope: #40a4c4;
  --foursquare-pink: #f94877;
  --foursquare-navy: #073282;
  --foursquare-blue: #2d5be3;
  --yelp: #d32323;
  --swarm: #ffa633;
  --medium: #02b875;
  --skype: #00aff0;
  --skype-dark-blue: #0078d7;
  --android: #a4c639;
  --stumbleupon: #e94826;
  --flickr-pink: #f40083;
  --flickr-blue: #006add;
  --yahoo: #430297;
  --twitch: #9146ff;
  --soundcloud: #ff5500;
  --spotify: #1ed760;
  --spotify-dark-green: #1db954;
  --dribbble: #ea4c89;
  --slack-purple: #4a154b;
  --slack-blue: #36c5f0;
  --slack-green: #2eb67d;
  --slack-red: #e01e5a;
  --slack-yellow: #ecb22e;
  --reddit: #ff5700;
  --deviantart: #05cc47;
  --pocket: #ee4056;
  --quora: #2b6dad;
  --slideshare-orange: #e68523;
  --slideshare-blue: #00a0dc;
  --fivehundredpx: #0099e5;
  --vk: #4a76a8;
  --listly-orange: #df6d46;
  --listly-blue: #52b1b3;
  --vine: #00b489;
  --steam: #171a21;
  --discord: #5865f2;
  --telegram: #0088cc;
}
```

this was generated by Gemini.. needs reviewed and pruned (like deviantart, vine, etc.. we dont need those right?). Also what's missing? Bluesky?
