### ISSUE TITLE
Add scalable font size import

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#479]
prototype / demo https://codepen.io/argyleink/pen/Yzgbgzm

```css
@layer demo {
  .scaleable {
    h1, h2, h3, h4 {
      font-size: calc(1rem * pow(var(--scale, 1.4), var(--heading-scale)));
    }
    
    h1 { --heading-scale: 4 }
    h2 { --heading-scale: 3 }
    h3 { --heading-scale: 2 }
    h4 { --heading-scale: 1 }
  }
}
```
