### ISSUE TITLE
Animate details in normalize.css

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#532]
https://developer.chrome.com/docs/css-ui/animate-to-height-auto/

also add animated details
```css
@supports (interpolate-size: allow-keywords) {
    :root {
        interpolate-size: allow-keywords;
    }
    
    details {
        transition: height 0.5s ease;
        height: 2.5rem;
        
        &[open] {
            height: auto;
            overflow: clip; /* Clip off contents while animating */
        }
    }
}
```

_Originally posted by @argyleink in https://github.com/argyleink/open-props/issues/512#issuecomment-2361864293_
