### ISSUE TITLE
Support, aggregate and distribute `@function`

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#549]
```css
@function --light-dark(--light, --dark) {
	result: var(--light);
	
	@container style(--theme: dark) {
		result: var(--dark);
	}
	
	@container style(--theme: system) {
		@media (prefers-color-scheme: dark) {
			result: var(--dark);
		}
	}
}
```

Creating a way to import these and even postcss-jit-prop them, will be amazing
