### ISSUE TITLE
Bug: `field-sizing: content` Causes Unexpected Behavior in `<select>` Element

### ISSUE THREAD

**Issue by mobalti** [argyleink/open-props#551]
![Image](https://github.com/user-attachments/assets/dddeed12-0490-4b81-bade-313738c5b674)

Screenshot from [gradient.style](https://gradient.style/)

**Comment by argyleink** [comment]
ty, easily fixed and deployed 🙏🏻 

```css
@supports (field-sizing: content) {
  padding-inline-end: 4ch;
}
```

just add a little spacing if field-sizing available
