### ISSUE TITLE
Gradients Bug with JIT Props

### ISSUE THREAD

**Issue by mobalti** [argyleink/open-props#556]
When using `jit-props` with Open Props, gradients don’t render properly. It looks like `--gradient-space` isn’t being injected, so the gradients break unless you manually define it in `:root` or `html`.

```css
html {
  /* You must comment out one of these for the gradient to render correctly */
  /* --gradient-space: ; */
  /* --gradient-space: in oklab; */
}

body {
  background-image: var(--gradient-13);
}
```
Everything works fine when importing Open Props directly (without jit-props).

[StackBlitz demo link](https://stackblitz.com/edit/vitejs-vite-r1o5iusq?file=src%2Fstyle.css)
