### ISSUE TITLE
test out using a multiplier in the fluid sizes

### ISSUE THREAD

**Issue by argyleink** [argyleink/open-props#56]
some of the fluid sizes do most their scaling in the lower widths, while others in the larger widths. using a multiplier in the equation could enable controlling these flow points better, for hopefully a more linear experience between lower and upper bounds. 

```css
--font-size-fluid-1: clamp(1rem, 2vw, 1.5rem);

/* becomes */
--fluidity: 2vw;
@media (min-width: 1024px) { --fluidity: 4vw }

--font-size-fluid-1: clamp(1rem, var(--fluidity), 1.5rem);
```

too much? the fluid props are really fun to use, but i feel it needs a tiny bit more variety and a bit more consistency.
